version: '3'
services:
  db:
    image: mysql:8.0
    container_name: vollmed_db
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vollmed_api
    volumes:
      - vollmed:/var/lib/mysql
volumes:
  vollmed: